[package]
name = "rns-vpn"
description = "P2P Reticulum VPN"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
cidr = { version = "0.3.*", features = ["serde"] }
ed25519-dalek = { version = "2.*", features = ["pem", "pkcs8"] }
etherparse = "0.19.*"
ipnet = { version = "2.*", features = ["serde"] }
log = "0.4.*"
rand_core = { version = "0.6.*", features = ["getrandom"] }
riptun = { version = "0.1.*", default-features = false, features = ["tokio-impl"] }
serde = { version = "1.*", features = ["derive"] }
tokio = { version = "1.44.*", features = ["full"] }

[dependencies.reticulum]
git = "https://github.com/BeechatNetworkSystemsLtd/Reticulum-rs"
version = "0.1.*"

[workspace]
members = ["rns-vpn-client"]
